name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '9.0.4' # The JDK version to make available on the path.
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64
    - run: echo "Construction de l'application"
    - run: javac -cp "commons-cli-1.4.jar:." simplissimeCmdline.java  txnscript.java jdbcUnitUtilities.java
    - run: echo "Construction de la suite de tests"
    - run: javac -cp "junit-4.13.jar:hamcrest-2.2.jar:." unitTestTxnScript.java jdbcUnitUtilities.java  
    - run: echo "Execution de la suite de tests"
    - run: java -cp "junit-4.13.jar:hamcrest-2.2.jar:postgresql-42.2.5.jar:." org.junit.runner.JUnitCore unitTestTxnScript
    - run: echo "Execution de l'application"
    - run: java -cp "postgresql-42.2.5.jar:commons-cli-1.4.jar:." simplissimeCmdline
      
